sudo: require
services:
  - docker

before_install:
  - docker build -t ajaykedare/react-test -f ./client/Dockerfile.dev2 ./client

script:
  - docker run -e CI=true ajaykedare/react-test npm test

after_success:
  - docker build -t ajaykedare/multi-client ./client
  - docker build -t ajaykedare/multi-nginx ./nginx
  - docker build -t ajaykedare/multi-server ./server
  - docker build -t ajaykedare/multi-worker ./worker
  
  # Login to docker CLI
  - echo "Logging in to DOCKER CLI"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOKCER_ID" --password-stdin
  # Take those images and put them to the docker hub
  - docker push ajaykedare/multi-client 
  - docker push ajaykedare/multi-nginx
  - docker push ajaykedare/multi-server
  - docker push ajaykedare/multi-worker